ftven_sivideo_core:
    resource: "@FTVENSivideoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

ageorgin_test:
    resource: "@AgeorginTestBundle/Controller/"
    type:     annotation
    prefix:   /

# Activation de FOSRestBundle pour générer en auto les routes de toutes les actions du controller TestRestController
testrest:
    type: rest
    resource: Ageorgin\Bundle\TestBundle\Controller\TestRestController
    